version: "3"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && yarn install && bundle exec rake assets:clobber RAILS_ENV=production && RAILS_ENV=production bundle exec rake assets:precompile && RAILS_ENV=production rails s -p 80 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "80:80"
    depends_on:
      - db
